### ISSUE TITLE
Проверка правильности заполнения полей для водителей

### ISSUE THREAD

**Issue by kirzas** [sedovalx/taxi#47]
@sedovalx 
в рамках #44  ты уже исправлял "ошибки валидации", может тут другое, но на всякий случай ссылаюсь.
Сейчас при создании водителя ФИО не считаются обязательными, т.е. с сервера не приходит ошибка (см. скриншот), но при этом если остальные поля заполнить, то водитель все равно не создается.

![capture](https://cloud.githubusercontent.com/assets/10670155/7318918/4785ef42-ea99-11e4-81eb-cfd8ad7ad7e9.JPG)

**Comment by sedovalx** [comment]
Не создается с какой ошибкой?

**Comment by kirzas** [comment]
@sedovalx @hodkoff2 
Немного не так все :)
Создается без ФИО, надо эти поля сделать обязательными. Или Дима, скажи, должны ли поля быть обязательными. 

Не создается, если запись с таким же номером паспорта уже есть. Это логически правильно, но пользователь ошибки не видит, а на сервере такая ошибка:
play.api.Application$$anon$1: Execution exception[[PSQLException: ╬╪╚┴╩└: яютЄюЁ ■∙ххё  чэрўхэшх ъы■ўр эрЁє°рхЄ юуЁрэшўхэшх єэшъры№эюёЄш "idx_pass_uq"
  Detail: ╩ы■ў "(pass)=(345345)" єцх ёє∙хёЄтєхЄ.]]
        at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.8.jar:2.3.8]
        at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.8.jar:2.3.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.8.jar:2.3.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.8.jar:2.3.8]
        at scala.Option.map(Option.scala:146) [scala-library-2.11.6.jar:na]
Caused by: org.postgresql.util.PSQLException: ╬╪╚┴╩└: яютЄюЁ ■∙ххё  чэрўхэшх ъы■ўр эрЁє°рхЄ юуЁрэшўхэшх єэшъры№эюёЄш "idx_pass_uq"
  Detail: ╩ы■ў "(pass)=(345345)" єцх ёє∙хёЄтєхЄ.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420) ~[postgresql-9.4-1201-jdbc41.jar:9.4]

**Comment by sedovalx** [comment]
@hodkoff2 должны ли поля быть обязательными?

**Comment by hodkovdd** [comment]
@Argelein @sedovalx 
должны быть обязательными!

**Comment by sedovalx** [comment]
@hodkoff2 @Argelein отчество не должно быть обязательным, т.к. не у всех оно есть.
